# makkefile begins

JFLAGS = -g
JC = javac
JVM= java 
FILE="config.txt"


.SUFFIXES: .java .class

.java.class:
        $(JC) $(JFLAGS) $*.java


CLASSES = \
        Stage1.java \
        State.java \
        Door.java \
        Window.java \
        Sensor.java \
	MagneticSensor.java \
	SwitchState.java


MAIN = Experiment 

default: classes

classes: $(CLASSES:.java=.class)


run: $(MAIN).class
	$(JVM) $(MAIN) $(FILE)


clean:
        $(RM) *.class
